--- #YAML:1.0
name:                Geo-Coordinates-UTM
version:             0.06
abstract:            Convert LatLon to UTM and vice versa
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Graham Crookham (grahamc@cpan.org)
distribution_type:   module
requires:     
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
